### ISSUE TITLE
Error when running example code

### ISSUE THREAD

**Issue by avishais** [snphbaum/scikit-gpuppy#3]
Hi,
When running the example code on the front page, I get 

> Exception ValueError: "Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'" in 'skgpuppy.UncertaintyPropagation2.UncertaintyPropagationApprox.propagate_mean' ignored
Traceback (most recent call last):
  File "test.py", line 58, in <module>
    out_mean, out_variance = up.propagate_GA(mean,Sigma)
  File "UncertaintyPropagation2.pyx", line 266, in skgpuppy.UncertaintyPropagation2.UncertaintyPropagationApprox.propagate_GA (skgpuppy/UncertaintyPropagation2.c:6461)
  File "UncertaintyPropagation2.pyx", line 289, in skgpuppy.UncertaintyPropagation2.UncertaintyPropagationApprox.propagate_GA (skgpuppy/UncertaintyPropagation2.c:6250)
  File "UncertaintyPropagation2.pyx", line 259, in skgpuppy.UncertaintyPropagation2.UncertaintyPropagationApprox._get_sigma2_and_variance_rest (skgpuppy/UncertaintyPropagation2.c:5718)
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'

What can I do?
Thanks.

**Comment by snphbaum** [comment]
Unfortunately, I have no time right now to actively maintain this project and to take care of that bug. I suggest it might be an issue with Cython. You can try to modify the setup.py and set USE_CYTHON manually to false. Then an alternative pure python implementation will be used. (Which is much slower unfortunately). (There is also a deprecated scipy weave implementation.)

**Comment by avishais** [comment]
Thank you very much, I understand. I was able to overcome this by directly working from the files without the installation. 
However, the output of the propagation is one dimensional although the state space is 2-d. Perhaps you have any directions on that? 
Thanks again.
